spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Admin1!
spring.jpa.hibernate.ddl-auto=update

# klucz jawny do celów testowych
jwt.secret=5f4dcc3b5aa765d61d8327deb882cf992257bdfe8da52f361ea8b212f46517a6

cors.allowed-origins=http://localhost:3000,[http://192.168.0.100:3000](http://192.168.0.100:3000)